export const statusOptions = {
  statusCategoria: [
    { value: 1, label: 'Ativo' },
    { value: 2, label: 'Desabilitado' },
  ],
  statusFornecedor: [
    { value: 1, label: 'Ativo' },
    { value: 2, label: 'Inativo' },
  ],
  statusJogo: [
    { value: 1, label: 'Ativo' },
    { value: 2, label: 'Inativo' },
  ],
  statusColecao: [
    { value: 1, label: 'Ativo' },
    { value: 2, label: 'Inativo' },
  ],
  statusProduto: [
    { value: 1, label: 'Ativo' },
    { value: 2, label: 'Fora de estoque' },
    { value: 3, label: 'Aguardando entrega' },
  ],
  statusCompra: [
    { value: 1, label: 'Pendente' },
    { value: 2, label: 'Confirmada' },
    { value: 3, label: 'Cancelada' },
  ],
  tipoMovimentacao: [
    { value: 1, label: 'Entrada' },
    { value: 2, label: 'Saida' },
  ],
}

export const resourceDefinitions = {
  categorias: {
    title: 'Categorias',
    endpoint: '/api/categoria',
    idKey: 'idCategoria',
    emptyLabel: 'categoria',
    lookupLabelKeys: ['nome'],
    createDefaults: { nome: '', descricao: '' },
    updateStatusKey: 'statusCategoria',
    fields: [
      { name: 'nome', label: 'Nome', required: true },
      { name: 'descricao', label: 'Descricao', type: 'textarea' },
    ],
    columns: [
      { key: 'idCategoria', label: 'ID' },
      { key: 'nome', label: 'Nome' },
      { key: 'descricao', label: 'Descricao' },
      { key: 'statusCategoria', label: 'Status', format: 'statusCategoria' },
    ],
  },
  jogos: {
    title: 'Jogos TCG',
    endpoint: '/api/jogo',
    idKey: 'idJogoTCG',
    emptyLabel: 'jogo',
    lookupLabelKeys: ['nome', 'fabricante'],
    createDefaults: { nome: '', fabricante: '' },
    updateStatusKey: 'statusJogo',
    fields: [
      { name: 'nome', label: 'Nome', required: true },
      { name: 'fabricante', label: 'Fabricante' },
    ],
    columns: [
      { key: 'idJogoTCG', label: 'ID' },
      { key: 'nome', label: 'Nome' },
      { key: 'fabricante', label: 'Fabricante' },
      { key: 'statusJogo', label: 'Status', format: 'statusJogo' },
    ],
  },
  fornecedores: {
    title: 'Fornecedores',
    endpoint: '/api/fornecedor',
    idKey: 'idFornecedor',
    emptyLabel: 'fornecedor',
    lookupLabelKeys: ['nome', 'cpfcnpj'],
    createDefaults: { nome: '', cpfcnpj: '', email: '', telefone: '' },
    updateStatusKey: 'statusFornecedor',
    fields: [
      { name: 'nome', label: 'Nome', required: true },
      { name: 'cpfcnpj', label: 'CPF/CNPJ', required: true },
      { name: 'email', label: 'E-mail', type: 'email', required: true },
      { name: 'telefone', label: 'Telefone', required: true },
    ],
    columns: [
      { key: 'idFornecedor', label: 'ID' },
      { key: 'nome', label: 'Nome' },
      { key: 'cpfcnpj', label: 'CPF/CNPJ' },
      { key: 'email', label: 'E-mail' },
      { key: 'telefone', label: 'Telefone' },
      { key: 'statusFornecedor', label: 'Status', format: 'statusFornecedor' },
    ],
  },
  colecoes: {
    title: 'Colecoes',
    endpoint: '/api/colecao',
    idKey: 'idColecao',
    emptyLabel: 'colecao',
    lookupLabelKeys: ['nome', 'sigla'],
    createDefaults: { nome: '', sigla: '', idJogoTCG: '', dataLancamento: '' },
    updateStatusKey: 'statusColecao',
    fields: [
      { name: 'nome', label: 'Nome', required: true },
      { name: 'sigla', label: 'Sigla' },
      { name: 'idJogoTCG', label: 'Jogo', lookup: 'jogos', required: true },
      { name: 'dataLancamento', label: 'Lancamento', type: 'date', required: true },
    ],
    columns: [
      { key: 'idColecao', label: 'ID' },
      { key: 'nome', label: 'Nome' },
      { key: 'sigla', label: 'Sigla' },
      { key: 'idJogoTCG', label: 'Jogo', lookup: 'jogos' },
      { key: 'dataLancamento', label: 'Lancamento', format: 'date' },
      { key: 'statusColecao', label: 'Status', format: 'statusColecao' },
    ],
  },
  produtos: {
    title: 'Produtos',
    endpoint: '/api/produto',
    idKey: 'idProduto',
    emptyLabel: 'produto',
    lookupLabelKeys: ['nome'],
    createDefaults: {
      nome: '',
      descricao: '',
      precoCusto: '',
      precoVenda: '',
      idCategoria: '',
      idJogoTCG: '',
      idColecao: '',
    },
    updateStatusKey: 'statusProduto',
    fields: [
      { name: 'nome', label: 'Nome', required: true },
      { name: 'descricao', label: 'Descricao', type: 'textarea' },
      { name: 'precoCusto', label: 'Custo', type: 'number', step: '0.01', required: true },
      { name: 'precoVenda', label: 'Venda', type: 'number', step: '0.01', required: true },
      { name: 'idCategoria', label: 'Categoria', lookup: 'categorias', required: true },
      { name: 'idJogoTCG', label: 'Jogo', lookup: 'jogos', required: true },
      { name: 'idColecao', label: 'Colecao', lookup: 'colecoes' },
    ],
    columns: [
      { key: 'idProduto', label: 'ID' },
      { key: 'nome', label: 'Nome' },
      { key: 'precoCusto', label: 'Custo', format: 'currency' },
      { key: 'precoVenda', label: 'Venda', format: 'currency' },
      { key: 'idCategoria', label: 'Categoria', lookup: 'categorias' },
      { key: 'idJogoTCG', label: 'Jogo', lookup: 'jogos' },
      { key: 'statusProduto', label: 'Status', format: 'statusProduto' },
    ],
  },
}
